### ISSUE TITLE
Initialize base project by copying spark from lbc code

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#1]
We should generate a Studio Project and add the modules from the LBC android-app

```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/173
- [ ] https://github.com/adevinta/spark-android/issues/174
- [ ] https://github.com/adevinta/spark-android/issues/156
- [ ] https://github.com/adevinta/spark-android/issues/175
- [ ] https://github.com/adevinta/spark-android/issues/176
- [ ] https://github.com/adevinta/spark-android/issues/178
- [ ] https://github.com/adevinta/spark-android/issues/179
- [ ] https://github.com/adevinta/spark-android/issues/180
- [ ] https://github.com/adevinta/spark-android/issues/181
- [ ] https://github.com/adevinta/spark-android/issues/149
- [ ] https://github.com/adevinta/spark-android/issues/150
- [ ] https://github.com/adevinta/spark-android/issues/182
- [ ] https://github.com/adevinta/spark-android/issues/183
- [ ] https://github.com/adevinta/spark-android/issues/185
- [ ] https://github.com/adevinta/spark-android/issues/153
- [ ] https://github.com/adevinta/spark-android/issues/161
- [ ] https://github.com/adevinta/spark-android/issues/160
- [ ] https://github.com/adevinta/spark-android/issues/186
- [ ] https://github.com/adevinta/spark-android/issues/187
- [ ] https://github.com/adevinta/spark-android/issues/158
- [x] Add Spacer
- [ ] https://github.com/adevinta/spark-android/issues/177
- [ ] https://github.com/adevinta/spark-android/issues/188
- [ ] https://github.com/adevinta/spark-android/issues/154
- [ ] https://github.com/adevinta/spark-android/issues/189
- [ ] https://github.com/adevinta/spark-android/issues/159
- [x] Add Toggles
```
