### ISSUE TITLE
[Component] Divider

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#1077]
```[tasklist]
### Tasks
- [x] Add and implementation & variants
- [x] Add the label support
- [x] Add screenshot testing
- [x] Add Documentation
- [x] Add Examples
- [ ] Add New configurator
```

**Comment by thomas-leguellec** [comment]
One comment in the Figma file
