### ISSUE TITLE
Build the catalog app

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#209]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/210
- [ ] https://github.com/adevinta/spark-android/issues/220
- [ ] https://github.com/adevinta/spark-android/issues/221
- [ ] https://github.com/adevinta/spark-android/issues/222
- [ ] https://github.com/adevinta/spark-android/issues/223
- [ ] https://github.com/adevinta/spark-android/issues/224
- [ ] https://github.com/adevinta/spark-android/issues/597
- [ ] https://github.com/adevinta/spark-android/issues/714
```
