### ISSUE TITLE
[Components] Button integration

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#268]
```[tasklist]
### Tasks
- [x] Add FilledButton
- [x] Add OutlinedButton
- [x] Add TintedButton
- [x] Add GhostButton
- [x] Add ContrastButton
- [x] Add Intent support
- [x] Add size support
- [x] Regenerate screenshots
- [x] Update documentation
- [ ] Update Lint rule
```

**Comment by thomas-leguellec** [comment]
https://zeroheight.com/1186e1705/v/latest/p/34b742-button/b/32e1a2
