### ISSUE TITLE
[Components] Text-field integration

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#339]
```[tasklist]
### Tasks
- [x] Update colors [b8243d](https://github.com/adevinta/spark-android/commit/b8243d08af2411240d89125d08f00bf5865b855b)
- [x] Update the typograhies [386c151](https://github.com/adevinta/spark-android/commit/386c151a88078567a407704ee2fea2b173f4b273)
- [x] Update the layout / measurements [bc15584](https://github.com/adevinta/spark-android/commit/38aa99e34c76e833e9f093e7999a487150c1bb1b)
- [x] Add isLegacy conditions to shapes [2d75f6a](https://github.com/adevinta/spark-android/commit/2d75f6ad477c480b5fa89e7d94d0669eba60a915)
- [x] Add support for mandatory param [63b4d29](https://github.com/adevinta/spark-android/commit/63b4d29583b9024d7d321668e2784e452ce8082f)
- [x] Add support for success and alert intents [230b765](https://github.com/adevinta/spark-android/commit/230b765d5bb393a402ea6551e41fc9a77904c18c)
- [x] Replace Material Icons by Spark ones [230b765](https://github.com/adevinta/spark-android/commit/230b765d5bb393a402ea6551e41fc9a77904c18c)
- [x] Add minLines param support [ab6ffd6](https://github.com/adevinta/spark-android/commit/ab6ffd6c49c0b8720ebc9c3d43e3648049e7b81c)
- [x] Update the previews to represent the states [230b765](https://github.com/adevinta/spark-android/commit/230b765d5bb393a402ea6551e41fc9a77904c18c)
- [ ] https://github.com/adevinta/spark-android/issues/477
- [ ] https://github.com/adevinta/spark-android/issues/478
- [ ] https://github.com/adevinta/spark-android/issues/479
```

**Comment by thomas-leguellec** [comment]
Need more info about the Variants (2 icons).

**Comment by soulcramer** [comment]
- [x] Update colors
- [x] Update the typograhies
- [x] Update the layout / measurements
- [ ] Add support for mandatory param
- [ ] Add support for success and alert intents
- [ ] Add minLines param support
- [ ] Update the previews to represent the states
- [ ] Add paparazzi test to test every state possible
- [ ] Design review

**Comment by soulcramer** [comment]
Missing parts:
- [ ] Disabled & read-only states are different
- [ ] The counter is colored as the helper
- [ ] Only the MultilineTexfField has a remove content icon
- [ ] The leading, trailing dropdown plugin won't be available now
- [ ] Same for the trailing button and the plate one
