### ISSUE TITLE
[Components] Spinner

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#482]
```[tasklist]
### Tasks
- [ ] Update colors
- [ ] Update the layout / measurements
- [ ] Add isLegacy conditions to shapes
- [ ] Update Animations
- [ ] Add intents
- [ ] Update the previews to represent the states
- [ ] Update the Spinner documentation from the api changes
- [ ] Add paparazzi test for every Spinner state possible
- [ ] Design review for Spinner
```

**Comment by MarinaRomanova** [comment]
Already done and available in 0.3.0
