### ISSUE TITLE
[Component] Popover

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#485]
```[tasklist]
### Tasks
- [x] Use the RichTooltipBox as base
- [x] Update the previews to represent the states
- [x] Address the deprecated API in TooltipBox
- [x] Add slots for component placements
- [x] Update the Popover documentation from the api changes
- [x] Add paparazzi test for every Popover state possible
```

**Comment by turolopezsanabria** [comment]
alright, FYI
https://github.com/adevinta/spark/issues/1360

**Comment by kazaky** [comment]
CC
https://github.com/adevinta/spark/issues/1585

**Comment by elisa-hery** [comment]
ℹ️ tests will be done by @kazaky. 
We agreed that importants things to test that are not visible on demo app are : 
- with or without tip
- with short / long text in the container (to test scrolling)
- alignment left/right/start/end
