### ISSUE TITLE
[Component] Progress-bar

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#486]
```[tasklist]
### Tasks
- [x] Update the previews to represent the states
- [ ] Update the Progressbar documentation from the api changes
- [x] Add paparazzi test for every Progressbar state possible
- [ ] Design review for Progressbar
- [x] Add Progressbar variants
- [x] Add Intent colors
- [x] Add border type
```
Specs: https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7229-1207&mode=design&t=hj5jj9tMlpz0sR53-0

**Comment by kazaky** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Does this ticket need to be tested ? | yes
Does this ticket need to be design reviewed ? | yes
Referent designer : | Jeremias
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7229-1207&mode=design&t=m8rm2yIaK6p49HaO-0)
UATs : | N/A
Snapshots scenarii : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+bar#Progressbar-snapshots)
demo app : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+bar#Progressbar-demo-app-configurator)
