### ISSUE TITLE
[Component] Slider

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#487]
```[tasklist]
### Tasks
- [x] Update colors
- [x] Update the layout / measurements
- [x] Update Animations
- [x] Add intents
- [x] Range slider
- [x] Add Configurator
- [x] Add paparazzi Screenshot tests
- [x] Add Documentation & Readme files
- [x] Fix deprecated functions after compose version upgrade
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | moderate *(should be tested by QAA before or after release)*
Does this ticket need to be design reviewed ? | yes
Referent designer : | @JeremiasUX 
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1rYA7PtmVfmNCi1GbfD-RIaSnrOfPQ4W3VMAke_ZWfDo/edit#gid=1859638032)
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=3409-22561&mode=design&t=JEgYOEd2ifXKSKKT-0)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Slider)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Slider#Slider-demo-app-configurator)
snapshots : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Slider#Slider-snapshots)

**Comment by elisa-hery** [comment]
@kazaky I just have 1 question : when I rotate the screen, slider "losts" its intent. Is it specific for catalog app or do you think it could happen on Polaris ?
https://github.com/adevinta/spark-android/assets/142396647/739f5bd8-3e64-4be7-81ef-036efae3a8f5


@JeremiasUX did you already test it ? it's available on catalog app if you want to !

**Comment by kazaky** [comment]
Hi @elisa-hery ,
It's a bug specific for Catalog App,
But I can check later how to improve this part.

Thanks for reporting
