### ISSUE TITLE
Refactor colors

### ISSUE THREAD

**Issue by MarinaRomanova** [adevinta/spark-android#554]
related to https://github.com/adevinta/spark-tokens/pull/56
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/555
- [ ] https://github.com/adevinta/spark-android/issues/556
- [ ] https://github.com/adevinta/spark-android/issues/557
```
