### ISSUE TITLE
[Tech] Release 0.5.0

### ISSUE THREAD

**Issue by MarinaRomanova** [adevinta/spark-android#622]
- [ ] Prepare and Publish Spark 0.5.0 to deliver IconButtons + ToggleableIconButtons
- [ ] Integrate 0.5.0 in Polaris
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/731
- [ ] https://github.com/adevinta/spark-android/issues/732
- [ ] https://github.com/adevinta/spark-android/issues/733
```

**Comment by SimonMarquis** [comment]
Nit: to target specific version, you could use GitHub's milestones.
