### ISSUE TITLE
[Component] ToggleIconButton

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#684]
Not specified yet but we need it for polaris.
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/609
- [ ] https://github.com/adevinta/spark-android/issues/634
- [ ] https://github.com/adevinta/spark/issues/1303
```
