### ISSUE TITLE
[Component] Rating

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#776]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/807
- [ ] https://github.com/adevinta/spark-android/issues/817
- [ ] https://github.com/adevinta/spark-android/issues/818
- [ ] https://github.com/adevinta/spark-android/issues/827
- [ ] https://github.com/adevinta/spark-android/issues/821
- [ ] https://github.com/adevinta/spark-android/issues/829
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Does this ticket need to be tested ? | yes
Does this ticket need to be design reviewed ? | yes
Referent designer : | Laura
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=7792-7244&mode=design&t=ZZFY1rwPpukfrZpN-0)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Rating#Rating-demo-app-configurator)

**Comment by elisa-hery** [comment]
Tested with @soulcramer and @Bibisirius : 
- disabled has not the right color, @soulcramer is going to improve it
- a textfield will be added in configurator to set the note

The rating will be part of the release anyway, so I'm closing this ticket and this will be handled in a bug ticket --> https://github.com/adevinta/spark/issues/1743
