### ISSUE TITLE
[Component] Progress tracker

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#780]
```[tasklist]
### Tasks
- [x] https://github.com/adevinta/spark-android/issues/977
- [x] https://github.com/adevinta/spark-android/issues/978
- [x] https://github.com/adevinta/spark-android/issues/979
- [x] https://github.com/adevinta/spark-android/issues/980
- [ ] https://github.com/adevinta/spark-android/issues/984
- [ ] https://github.com/adevinta/spark-android/issues/982
- [ ] https://github.com/adevinta/spark-android/issues/983
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | ℹ️ other stacks : moderate (= should be tested by QAA before or after release)
Does this ticket need to be design reviewed ? | yes
Referent designer : | @JeremiasUX 
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=12212-6713&mode=design&t=FvppNKarxpA4HxdE-0)
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1HAB4mAobEeHz1sJ8YihL-_HHt_OIiInYdWaCAZEj_ZM/edit#gid=1956428383)
UATs : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker)
configurator : | [confluence](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker#Progress+tracker-demo-app-configurator)
