### ISSUE TITLE
[Component] Dropdown

### ISSUE THREAD

**Issue by thomas-leguellec** [adevinta/spark-android#781]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/1138
- [ ] https://github.com/adevinta/spark-android/issues/1145
- [ ] https://github.com/adevinta/spark-android/issues/1150
- [ ] https://github.com/adevinta/spark-android/issues/1161
- [ ] https://github.com/adevinta/spark-android/issues/1157
- [ ] https://github.com/adevinta/spark-android/issues/1162
- [ ] https://github.com/adevinta/spark-android/issues/1163
- [ ] https://github.com/adevinta/spark-android/issues/1212
- [ ] https://github.com/adevinta/spark-android/issues/1164
```

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | TO DEFINE
Does this ticket need to be design reviewed ? | yes
Referent designer : | ?
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Component-Specs-of-Spark?type=design&node-id=28629-1833&mode=design&t=Qir237PAl1nm2R1a-0)
Testing checklist : | [TO DO](https://docs.google.com/spreadsheets/d/1HAB4mAobEeHz1sJ8YihL-_HHt_OIiInYdWaCAZEj_ZM/edit#gid=1956428383)
UATs : | [TO DO](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker)
configurator : | [TO DO](https://confluence.ets.mpi-internal.com/display/SPAR/Progress+tracker#Progress+tracker-demo-app-configurator)
