### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#849]
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/issues/850
- [ ] https://github.com/adevinta/spark-android/issues/851
- [x] [Release 0.6.0] Add fixes before snapshot release
- [ ] https://github.com/adevinta/spark-android/issues/852
- [ ] https://github.com/adevinta/spark-android/issues/858
- [ ] https://github.com/adevinta/spark-android/issues/861
```
