### ISSUE TITLE
Add support for Dokka in Github pages

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#89]
Based on the discussions in #25 we agreed to use Github pages to host the generated Dokka documentation.

```[tasklist]
### Tasks
- [ ] Add Dokka plugin in the project
- [ ] Makes the plugin generate the documentation
- [ ] Run the task to generate it on PR merge to main
- [ ] Host the generated documentation on Github Pages
```
