### ISSUE TITLE
[bug] [Rating] update disabled state

### ISSUE THREAD

**Issue by elisa-hery** [adevinta/spark-android#910]
1) Disabled state is not visible enough : 

![Image](https://github.com/adevinta/spark/assets/142396647/991d3241-0d00-4b95-9d8a-55d2fd392190)

2) @soulcramer will also add a textfield to configurator to test more options --> EDIT : this part is done ✅ 
```[tasklist]
### Tasks
- [x] Adding Enabled state to Rating input function, change how RatingStar renders color
- [x] Make the Rating Star inline as it's not necessary for our consumers
- [x] Enhancements overall in Rating component implementation
```

**Comment by Bibisirius** [comment]
Tested and approved! ✅ 
Thank you @elisa-hery @kazaky
