### ISSUE TITLE
[Avatar] Add Large size

### ISSUE THREAD

**Issue by amokhefi** [adevinta/spark-android#918]
### 🕵️ Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

The current avatar component sizes available do not cater to all requirements. There is a need for an additional size, especially when wrapping the avatar inside a box with the `fillParentSize` attribute set to true. This setup triggers an issue where the `PresenceIndicator` is not correctly aligned.

### Describe the solution

Add new `UserAvatarStyle` for large size with the appropriate parameters

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/adevinta/spark-android/pull/919
```
