### ISSUE TITLE
[Component] BottomSheet

### ISSUE THREAD

**Issue by Bibisirius** [adevinta/spark-android#929]
```[tasklist]
### Tasks
- [x] Update the layout / measurements
- [x] Add Expandable / Non exandapable
- [x] Add Configurator
- [x] Request: Check if it's possible to not have padding on the top and bottom with and without drag handle
- [x] Add Examples
- [x] Add Documentation & Readme files
- [ ] https://github.com/adevinta/spark-android/issues/1039
```

Spec Figma : [url](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=8718-2815&mode=design&t=l8XWl1AXEZQd9TnE-11)

Note: Explore the possibility of deleting shapes when the bottom sheet is in full screen mode

**Comment by elisa-hery** [comment]
<google-sheets-html-origin>

Testing informations |  
-- | --
Risk level ? | TO DEFINE
Does this ticket need to be design reviewed ? | yes
Referent designer : | @Bibisirius 
Testing checklist : | [gsheet](https://docs.google.com/spreadsheets/d/1hjUgo98H1-l4mItL4SdWJ48dgjNMbtKSQIjeoYjbnfo/edit#gid=1926623587)
Spec : | [figma](https://www.figma.com/file/0QchRdipAVuvVoDfTjLrgQ/Spark-Specs-and-Handoff?type=design&node-id=3409-22561&mode=design&t=JEgYOEd2ifXKSKKT-0)
UATs : | [gsheet](https://docs.google.com/spreadsheets/d/1hjUgo98H1-l4mItL4SdWJ48dgjNMbtKSQIjeoYjbnfo/edit#gid=53063058)
configurator : | [to add](https://confluence.ets.mpi-internal.com/display/SPAR/Slider#Bottomsheet-demo-app-configurator)
snapshots : | [to add](https://confluence.ets.mpi-internal.com/display/SPAR/Slider#Bottomsheet-snapshots)

**Comment by Bibisirius** [comment]
Request: 
Check if it's possible to not have padding on the top and bottom with and without drag handle


Example: We need he possibility to not have padding on the top with the drag handle 
![Image](https://github.com/adevinta/spark-android/assets/139967199/ff44b8b1-e9c8-45ba-86f7-0b434b100ffa)

**Comment by Bibisirius** [comment]
We provide that it's possible to have the option of not having padding in the content (body) ✅

**Comment by elisa-hery** [comment]
Remarks after testing : 
1. on mobile / landscape, content of the page overflows below the bottomsheet. IMO this should be fixed before release it.

<img src="https://github.com/adevinta/spark-android/assets/142396647/7bedb07e-c630-444d-9ba6-af15de3dc82a" alt="isolated" width="500"/>


<br/><br/>

2. remark : when body is too big content, scroll is possible but we cannot see the scroll bar (seen with @kazaky : it's normal / default behavior but we could show it. WDYT @Bibisirius ?)

<img src="https://github.com/adevinta/spark-android/assets/142396647/3a7089ca-5334-449e-b1f5-3af8db4d8436" alt="isolated" width="500"/>

<br/><br/>

3. we don't have 48px at the top of the screen like asked in the specs (discussed with @kazaky --> it's default behaviors from Material design library, though the height can be easily adjusted by consumers. Is it ok for you @Bibisirius ?)

**Comment by kazaky** [comment]
Created a bug ticket for 1 
https://github.com/adevinta/spark-android/issues/1039

**Comment by Bibisirius** [comment]
@elisa-hery @kazaky 
1. yes we have to wait for bug to be fixed before release
2. we should have the possibility to add scroll bar @kazaky
3. OK to keep it as it is
4. no close icon on android

**Comment by kazaky** [comment]
@Bibisirius @elisa-hery

> we should have the possibility to add scroll bar
This is just a random content example I created,
your request is not related to BottomSheet,
In user's case they should be able to provide scrollbar for their content

**Comment by elisa-hery** [comment]
Since PR is still in review, I will close the bug ticket https://github.com/adevinta/spark-android/issues/1039 and move this ticket back to "in progress" (time to fix the landscape bug)
