### ISSUE TITLE
Prepare release 0.7.0

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#960]
```[tasklist]
### Tasks
- [ ] [Release 0.7.0] Modify ChangeLog
- [ ] [Release 0.7.0] Test release change locally
- [ ] [Release 0.7.0] Add fixes before snapshot release
- [ ] [Release 0.7.0] Create a snapshot used in Polaris
```
