### ISSUE TITLE
Remove legacy themes mentions from the tokens and components

### ISSUE THREAD

**Issue by soulcramer** [adevinta/spark-android#971]
During the Compose Migration of Polaris I've added a CompositionLocal that will apply different styles depending on it to respect the previous UI we had in Polaris and avoid 2 different style from being visible on a screen.

The migration being close to the end we can now safely remove this flags from our codebase

```[tasklist]
### Tasks
- [x] Remove `LocalLegacyStyle` from the code base and only use the current style where it was used
- [x] Remove the legacy theme from the catalog app
- [x] Remove the deprecated `TextButton`
- [x] Remove the deprecated `AssistChip`, `FilterChip`, `InputChip`, `SuggestionChip`
- [x] Remove the deprecated `TagPromote`, `TagUrgent`, `TagPro`
```
